Feature/products
Grungeshum/ice-cream-project pull request #3
Opened 2022-06-10 21:12 UTC by mrn2022mlcn

Добавила код из своего репозитория, но стили не отображаются. Если можешь, посмотри, в чем проблема

2022-06-11 17:31 UTC, Grungeshum requested changes
треба видалити вайлs index.css  і index.css.map. Ми з ними не працюємо.
І там ще два фікси по letter-spacing
ДЯкую

2022-06-11 17:31 UTC, Grungeshum commented on src/sass/_products.scss
> +    letter-spacing: 0.04%;
тут має бути em  замість %

2022-06-11 17:31 UTC, Grungeshum commented on src/sass/_products.scss
> +    letter-spacing: 0.04%;
тут так само

2022-06-11 18:41 UTC, mrn2022mlcn commented
Дякую, зараз повиправляю

сб, 11 черв. 2022 р. о 20:31 Igor Mazur ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
>
> треба видалити вайлs index.css і index.css.map. Ми з ними не працюємо.
> І там ще два фікси по letter-spacing
> ДЯкую
> ------------------------------
>
> In src/sass/_products.scss
> <https://github.com/Grungeshum/ice-cream-project/pull/3#discussion_r895048882>
> :
>
> > +    }
>
> +    &:nth-child(3n) {
>
> +        background-color:#C2E297;
>
> +    }
>
> +}
>
> +
>
> +
>
> +.item__title {
>
> +    padding-top: 160px;
>
> +    padding-right: 53px;
>
> +    padding-left: 53px;
>
> +    margin-bottom: 32px;
>
> +    text-align: center;
>
> +    font-size: 20px;
>
> +    line-height: 1.15;
>
> +    letter-spacing: 0.04%;
>
>
> тут має бути em замість %
> ------------------------------
>
> In src/sass/_products.scss
> <https://github.com/Grungeshum/ice-cream-project/pull/3#discussion_r895048935>
> :
>
> > +    margin-left: auto;
>
> +    display: block;
>
> +    width: 25px;
>
> +    height: 6px;
>
> +    background-image: url(/images/Group\ 4-min.svg);
>
> +}
>
> +}
>
> +
>
> +
>
> +.item__text {
>
> +    margin: 32px auto;
>
> +    width: 200px;
>
> +    height: 124px;
>
> +    font-size: 14px;
>
> +    line-height: 1.79;
>
> +    letter-spacing: 0.04%;
>
>
> тут так само
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Grungeshum/ice-cream-project/pull/3#pullrequestreview-1003482529>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXOIJBRKPAL4KQASIU2BGGDVOTEPBANCNFSM5YO4DBYA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-12 18:43 UTC, closed without merging

2022-06-12 18:44 UTC, Grungeshum commented
зроби новий пул. В існуючому є конфлікти та дубляж коду