Feature/about
Grungeshum/ice-cream-project pull request #8
Opened 2022-06-11 18:22 UTC by MysOlha

Готовий варіант

2022-06-11 19:27 UTC, Grungeshum requested changes
пофікси заголовок пліз

2022-06-11 19:27 UTC, Grungeshum commented on src/partials/about.html
> +        <h3 class="about__first-tittle">tradition and love</h3>
tradition and love – є лейблом заголовка і не виділяється тегом заголовка

2022-06-11 19:53 UTC, MysOlha commented on src/partials/about.html
> +        <h3 class="about__first-tittle">tradition and love</h3>
виправила, не робила спочатку лейбл, бо ментор казав, щоб ми робили Н2 і Н3

2022-06-12 09:03 UTC, Grungeshum approved these changes

2022-06-12 09:06 UTC, merged